Repository Stumeet/STUMEET-SERVER, pull requests merged in 2024-03, with the labels that each got.

#76 🔨 [STMT-6] fork repository를 위한 CI workflow 구축
  .github/workflows/ci.yml
  .github/workflows/ci_trigger.yml
Labels: D-0

#79 🔨 [STMT-6] fork repository를 위한 CI workflow 구축 - 에러 해결
  .github/workflows/ci-trigger.yml
  .github/workflows/ci.yml
Labels: D-1

#86 :rewind: [STMT-6] 기존 CI 워크플로우로 되돌리기
  .github/workflows/ci-trigger.yml
  .github/workflows/ci.yml
Labels: D-0

#88 :sparkles: [STMT-89] 당도 -> 레벨 변경으로 인한 스키마 구조 변경 및 코드 대응
  src/main/java/com/stumeet/server/member/adapter/out/persistence/MemberJpaEntity.java
  src/main/java/com/stumeet/server/member/adapter/out/persistence/MemberPersistenceMapper.java
  src/main/java/com/stumeet/server/member/application/service/MemberOAuthService.java
  src/main/java/com/stumeet/server/member/domain/Member.java
  src/main/java/com/stumeet/server/member/domain/MemberLevel.java
  src/main/java/com/stumeet/server/member/domain/MemberRank.java
  src/main/resources/db/migration/V1.2__modify_member_level.sql
  src/test/java/com/stumeet/server/stub/MemberStub.java
Labels: D-0

#95 :bug: [STMT-146] 멤버 레벨을 표현하기 위한 rank 칼럼의 DB 예약어로 인한 insert 쿼리 실패 버그 해결
  src/main/java/com/stumeet/server/member/adapter/in/web/response/MemberProfileResponse.java
  src/main/java/com/stumeet/server/member/adapter/out/persistence/MemberJpaEntity.java
  src/main/java/com/stumeet/server/member/adapter/out/persistence/MemberPersistenceMapper.java
  src/main/java/com/stumeet/server/member/application/port/in/mapper/MemberUseCaseMapper.java
  src/main/java/com/stumeet/server/member/application/service/MemberOAuthService.java
  src/main/java/com/stumeet/server/member/domain/MemberLevel.java
  src/main/java/com/stumeet/server/member/domain/MemberTier.java
  src/main/resources/db/migration/V1.3__modify_column_rank_to_tier.sql
  src/test/java/com/stumeet/server/member/adapter/in/web/MemberProfileApiTest.java
  src/test/java/com/stumeet/server/stub/MemberStub.java
  src/test/resources/db/setup.sql
Labels: D-0

#96 :bug: [STMT-146] 멤버 레벨을 표현하기 위한 rank 칼럼의 DB 예약어로 인한 insert 쿼리 실패 버그 해결
  src/main/java/com/stumeet/server/member/adapter/in/web/response/MemberProfileResponse.java
  src/main/java/com/stumeet/server/member/adapter/out/persistence/MemberJpaEntity.java
  src/main/java/com/stumeet/server/member/adapter/out/persistence/MemberPersistenceMapper.java
  src/main/java/com/stumeet/server/member/application/port/in/mapper/MemberUseCaseMapper.java
  src/main/java/com/stumeet/server/member/application/service/MemberOAuthService.java
  src/main/java/com/stumeet/server/member/domain/MemberLevel.java
  src/main/java/com/stumeet/server/member/domain/MemberTier.java
  src/main/resources/db/migration/V1.3__modify_column_rank_to_tier.sql
  src/test/java/com/stumeet/server/member/adapter/in/web/MemberProfileApiTest.java
  src/test/java/com/stumeet/server/stub/MemberStub.java
  src/test/resources/db/setup.sql
Labels: D-0

#92 ✨ [STMT-200] 스터디 도메인 구현
  src/main/java/com/stumeet/server/common/model/ApiResponse.java
  src/main/java/com/stumeet/server/common/response/ErrorCode.java
  src/main/java/com/stumeet/server/common/response/SuccessCode.java
  src/main/java/com/stumeet/server/study/adapter/in/web/StudyQueryApi.java
  src/main/java/com/stumeet/server/study/adapter/in/web/response/StudyDetailResponse.java
  src/main/java/com/stumeet/server/study/adapter/out/persistance/JpaStudyRepository.java
  src/main/java/com/stumeet/server/study/adapter/out/persistance/StudyPersistenceAdapter.java
  src/main/java/com/stumeet/server/study/adapter/out/persistance/StudyRepository.java
  src/main/java/com/stumeet/server/study/adapter/out/persistance/StudyRepositoryImpl.java
  src/main/java/com/stumeet/server/study/adapter/out/persistance/entity/StudyFieldJpaEntity.java
  src/main/java/com/stumeet/server/study/adapter/out/persistance/entity/StudyJpaEntity.java
  src/main/java/com/stumeet/server/study/adapter/out/persistance/mapper/StudyFieldPersistenceMapper.java
  src/main/java/com/stumeet/server/study/adapter/out/persistance/mapper/StudyPersistenceMapper.java
  src/main/java/com/stumeet/server/study/application/port/in/StudyQueryUseCase.java
  src/main/java/com/stumeet/server/study/application/port/out/StudyQueryPort.java
  src/main/java/com/stumeet/server/study/application/port/out/mapper/StudyUseCaseMapper.java
  src/main/java/com/stumeet/server/study/application/service/StudyQueryService.java
  src/main/java/com/stumeet/server/study/domain/Study.java
  src/main/java/com/stumeet/server/study/domain/StudyField.java
  src/main/java/com/stumeet/server/study/domain/StudyHeadCount.java
  src/main/java/com/stumeet/server/study/domain/StudyPeriod.java
  src/main/java/com/stumeet/server/study/domain/StudyTopics.java
  src/main/resources/db/migration/V1.4__add_study_table.sql
  src/main/resources/db/migration/V1.5_insert_dummy_study_data.sql
Labels: D-0

#93 ✅ [STMT-146] 소셜 로그인시 전달한 JWT 토큰의 서명이 유효하지 않은 경우에 대한 핸들링 추가
  src/docs/asciidoc/index.adoc
  src/main/java/com/stumeet/server/common/auth/exception/IllegalKeyAlgorithmException.java
  src/main/java/com/stumeet/server/common/auth/exception/JwtInvalidSignatureException.java
  src/main/java/com/stumeet/server/common/auth/exception/JwtTokenParsingException.java
  src/main/java/com/stumeet/server/common/client/oauth/apple/AppleIdTokenProvider.java
  src/main/java/com/stumeet/server/common/response/ErrorCode.java
  src/test/java/com/stumeet/server/common/auth/filter/OAuthAuthenticationFilterTest.java
  src/test/java/com/stumeet/server/stub/MemberStub.java
  src/test/java/com/stumeet/server/stub/TokenStub.java
Labels: D-0

#89 🚧 [STMT-146] 파일 업로드 기능 코드 리뷰 반영
  src/main/java/com/stumeet/server/common/annotation/validator/NullOrImageFileValidator.java
  src/main/java/com/stumeet/server/common/exception/model/BusinessException.java
  src/main/java/com/stumeet/server/common/exception/model/InvalidFileException.java
  src/main/java/com/stumeet/server/common/exception/model/NotImplementedException.java
  src/main/java/com/stumeet/server/common/response/ErrorCode.java
  src/main/java/com/stumeet/server/common/response/SuccessCode.java
  src/main/java/com/stumeet/server/common/util/FileUtil.java
  src/main/java/com/stumeet/server/common/util/FileValidator.java
  src/main/java/com/stumeet/server/file/adapter/out/S3ImageStorageAdapter.java
  src/main/java/com/stumeet/server/file/application/port/in/FileUploadUseCase.java
  src/main/java/com/stumeet/server/file/application/port/out/FileCommandPort.java
  src/main/java/com/stumeet/server/file/application/service/FileUploadService.java
  src/main/java/com/stumeet/server/file/domain/ImageContentType.java
Labels: D-0

#99 :bug: [STMT-146] 표준 예외가 아닌 커스텀 예외를 사용하도록 변경
  src/main/java/com/stumeet/server/common/auth/exception/IllegalKeyAlgorithmException.java
  src/main/java/com/stumeet/server/common/auth/exception/NotExistsOAuthProviderException.java
  src/main/java/com/stumeet/server/common/client/oauth/apple/AppleIdTokenProvider.java
  src/main/java/com/stumeet/server/common/exception/model/NotExistsException.java
  src/main/java/com/stumeet/server/common/response/ErrorCode.java
  src/main/java/com/stumeet/server/member/adapter/out/persistence/MemberPersistenceAdapter.java
  src/main/java/com/stumeet/server/member/domain/OAuthProvider.java
  src/main/java/com/stumeet/server/member/domain/exception/MemberNotExistsException.java
Labels: D-1

#98 :sparkles: [STMT-220] 스터디 멤버 도메인 정의 및 스키마 추가
  src/main/java/com/stumeet/server/studymember/adapter/out/persistence/JpaStudyMemberRepository.java
  src/main/java/com/stumeet/server/studymember/adapter/out/persistence/StudyMemberJpaEntity.java
  src/main/java/com/stumeet/server/studymember/adapter/out/persistence/StudyMemberPersistenceMapper.java
  src/main/java/com/stumeet/server/studymember/domain/StudyMember.java
  src/main/resources/application-local.yml
  src/main/resources/application-prod.yml
  src/main/resources/db/migration/V1.7__add_study_member_table.sql
  src/test/resources/application.yml
Labels: D-1

#101 ✨[STMT-6] DEV용 access token을 받아오는 api 작성
  src/main/java/com/stumeet/server/common/auth/config/SecurityConfig.java
  src/main/java/com/stumeet/server/common/response/SuccessCode.java
  src/main/java/com/stumeet/server/dev/adapter/in/web/DevApi.java
  src/main/java/com/stumeet/server/dev/adapter/in/web/response/AccessTokenResponse.java
  src/main/java/com/stumeet/server/dev/application/service/DevService.java
Labels: D-0

#100 👷 [STMT-6] dev 브랜치에도 CI/CD 파이프라인이 실행되도록 변경
  .github/workflows/ci-cd.yml
Labels: D-0

#104 :construction_worker: [STMT-6] dev 브랜치에 push가 발생해도 서버 배포를 진행하도록 변경
  .github/workflows/ci-cd.yml
Labels: D-3

#105 ✨ [STMT-220] 스터디 멤버 조회 기능 구현
  src/docs/asciidoc/index.adoc
  src/main/java/com/stumeet/server/common/exception/model/InvalidStateException.java
  src/main/java/com/stumeet/server/common/response/ErrorCode.java
  src/main/java/com/stumeet/server/studymember/adapter/in/web/StudyMemberQueryApi.java
  src/main/java/com/stumeet/server/studymember/adapter/out/persistence/JpaStudyMemberRepository.java
  src/main/java/com/stumeet/server/studymember/adapter/out/persistence/JpaStudyMemberRepositoryCustom.java
  src/main/java/com/stumeet/server/studymember/adapter/out/persistence/JpaStudyMemberRepositoryCustomImpl.java
  src/main/java/com/stumeet/server/studymember/adapter/out/persistence/StudyMemberPersistenceAdapter.java
  src/main/java/com/stumeet/server/studymember/application/port/in/StudyMemberQueryUseCase.java
  src/main/java/com/stumeet/server/studymember/application/port/in/StudyMemberValidationUseCase.java
  src/main/java/com/stumeet/server/studymember/application/port/in/response/SimpleStudyMemberResponse.java
  src/main/java/com/stumeet/server/studymember/application/port/in/response/StudyMemberResponses.java
  src/main/java/com/stumeet/server/studymember/application/port/out/StudyMemberQueryPort.java
  src/main/java/com/stumeet/server/studymember/application/port/out/StudyMemberValidationPort.java
  src/main/java/com/stumeet/server/studymember/application/service/StudyMemberQueryService.java
  src/main/java/com/stumeet/server/studymember/application/service/StudyMemberValidationService.java
  src/main/java/com/stumeet/server/studymember/domain/exception/StudyMemberNotJoinedException.java
  src/test/java/com/stumeet/server/helper/WithMockMember.java
  src/test/java/com/stumeet/server/stub/MemberStub.java
  src/test/java/com/stumeet/server/stub/StudyMemberStub.java
  src/test/java/com/stumeet/server/stub/StudyStub.java
  src/test/java/com/stumeet/server/studymember/adapter/in/web/StudyMemberQueryApiTest.java
  src/test/java/com/stumeet/server/studymember/adapter/out/persistence/JpaStudyMemberRepositoryCustomImplTest.java
  src/test/java/com/stumeet/server/studymember/application/service/StudyMemberQueryServiceTest.java
  src/test/java/com/stumeet/server/studymember/application/service/StudyMemberValidationServiceTest.java
  src/test/java/com/stumeet/server/studymember/application/service/integration/StudyMemberJoinServiceIntegrationTest.java
  src/test/resources/db/setup.sql
  src/test/resources/db/teardown.sql
Labels: D-0

#106 :card_file_box: [STMT-220] 테이블 `study_domain` 외래키 제약조건 변경 및 각 필드 데이터 크기 증대
  src/main/resources/db/migration/V1.4__add_study_table.sql
Labels: bug, D-1, hotfix

#103 :white_check_mark: [STMT-62] 스터디 상세 정보 조회 API 테스트 추가 및 명세서 작성
  src/docs/asciidoc/index.adoc
  src/test/java/com/stumeet/server/study/adapter/in/web/StudyQueryApiTest.java
Labels: D-0

#108 ✨ [STMT-193] 스터디 탈퇴 기능 구현
  src/docs/asciidoc/index.adoc
  src/main/java/com/stumeet/server/common/model/ApiResponse.java
  src/main/java/com/stumeet/server/common/response/SuccessCode.java
  src/main/java/com/stumeet/server/studymember/adapter/in/web/StudyMemberLeaveApi.java
  src/main/java/com/stumeet/server/studymember/adapter/out/persistence/JpaStudyMemberRepository.java
  src/main/java/com/stumeet/server/studymember/adapter/out/persistence/StudyMemberLeavePersistenceAdapter.java
  src/main/java/com/stumeet/server/studymember/application/port/in/StudyMemberLeaveUseCase.java
  src/main/java/com/stumeet/server/studymember/application/port/out/StudyMemberLeavePort.java
  src/main/java/com/stumeet/server/studymember/application/service/StudyMemberLeaveService.java
  src/test/java/com/stumeet/server/studymember/adapter/in/web/StudyMemberLeaveApiTest.java
  src/test/java/com/stumeet/server/studymember/application/service/StudyMemberLeaveServiceTest.java
Labels: D-1

#109 🩹 [STMT-62] 스터디 도메인 누락된 컬럼들 추가
  src/main/java/com/stumeet/server/study/adapter/in/web/response/StudyDetailResponse.java
  src/main/java/com/stumeet/server/study/adapter/out/persistance/entity/StudyJpaEntity.java
  src/main/java/com/stumeet/server/study/adapter/out/persistance/mapper/MeetingRepetitionPersistenceMapper.java
  src/main/java/com/stumeet/server/study/adapter/out/persistance/mapper/StudyPersistenceMapper.java
  src/main/java/com/stumeet/server/study/application/port/out/mapper/StudyUseCaseMapper.java
  src/main/java/com/stumeet/server/study/application/service/StudyQueryService.java
  src/main/java/com/stumeet/server/study/domain/ScheduleRepetitionType.java
  src/main/java/com/stumeet/server/study/domain/Study.java
  src/main/java/com/stumeet/server/study/domain/StudyMeetingSchedule.java
  src/main/resources/db/migration/V1.4__add_study_table.sql
  src/main/resources/db/migration/V1.6__insert_study_dummy_data.sql
  src/test/java/com/stumeet/server/study/adapter/in/web/StudyQueryApiTest.java
Labels: D-1
