Repository Stumeet/STUMEET-SERVER, pull requests merged in 2024-04, with the labels that each got.

#110 ✨ [STMT-192] 관리자 스터디 강퇴 기능 구현
  src/docs/asciidoc/index.adoc
  src/main/java/com/stumeet/server/common/response/ErrorCode.java
  src/main/java/com/stumeet/server/common/response/SuccessCode.java
  src/main/java/com/stumeet/server/studymember/adapter/in/web/StudyMemberLeaveApi.java
  src/main/java/com/stumeet/server/studymember/adapter/out/persistence/JpaStudyMemberRepository.java
  src/main/java/com/stumeet/server/studymember/adapter/out/persistence/JpaStudyMemberRepositoryCustom.java
  src/main/java/com/stumeet/server/studymember/adapter/out/persistence/JpaStudyMemberRepositoryCustomImpl.java
  src/main/java/com/stumeet/server/studymember/adapter/out/persistence/StudyMemberPersistenceAdapter.java
  src/main/java/com/stumeet/server/studymember/application/port/in/StudyMemberLeaveUseCase.java
  src/main/java/com/stumeet/server/studymember/application/port/in/StudyMemberValidationUseCase.java
  src/main/java/com/stumeet/server/studymember/application/port/out/StudyMemberValidationPort.java
  src/main/java/com/stumeet/server/studymember/application/service/StudyMemberLeaveService.java
  src/main/java/com/stumeet/server/studymember/application/service/StudyMemberValidationService.java
  src/main/java/com/stumeet/server/studymember/domain/exception/NotStudyAdminException.java
  src/test/java/com/stumeet/server/stub/StudyMemberStub.java
  src/test/java/com/stumeet/server/studymember/adapter/in/web/StudyMemberLeaveApiTest.java
  src/test/java/com/stumeet/server/studymember/application/service/StudyMemberLeaveServiceTest.java
Labels: D-2

#111 ✨ [STMT-62] 스터디 생성 기능 구현
  src/docs/asciidoc/index.adoc
  src/main/java/com/stumeet/server/common/exception/handler/GlobalExceptionHandler.java
  src/main/java/com/stumeet/server/common/exception/model/BadRequestException.java
  src/main/java/com/stumeet/server/common/exception/model/InvalidResourceException.java
  src/main/java/com/stumeet/server/common/response/ErrorCode.java
  src/main/java/com/stumeet/server/common/response/SuccessCode.java
  src/main/java/com/stumeet/server/common/util/FileValidator.java
  src/main/java/com/stumeet/server/file/application/port/in/FileUploadUseCase.java
  src/main/java/com/stumeet/server/file/application/service/FileUploadService.java
  src/main/java/com/stumeet/server/file/domain/exception/InvalidFileException.java
  src/main/java/com/stumeet/server/study/adapter/in/web/StudyCreateApi.java
  src/main/java/com/stumeet/server/study/adapter/in/web/StudyQueryApi.java
  src/main/java/com/stumeet/server/study/adapter/out/persistance/JpaStudyDomainRepository.java
  src/main/java/com/stumeet/server/study/adapter/out/persistance/JpaStudyFieldRepository.java
  src/main/java/com/stumeet/server/study/adapter/out/persistance/JpaStudyTagRepository.java
  src/main/java/com/stumeet/server/study/adapter/out/persistance/StudyDomainPersistenceAdapter.java
  src/main/java/com/stumeet/server/study/adapter/out/persistance/StudyFieldPersistenceAdapter.java
  src/main/java/com/stumeet/server/study/adapter/out/persistance/StudyPersistenceAdapter.java
  src/main/java/com/stumeet/server/study/adapter/out/persistance/StudyRepository.java
  src/main/java/com/stumeet/server/study/adapter/out/persistance/StudyRepositoryImpl.java
  src/main/java/com/stumeet/server/study/adapter/out/persistance/StudyTagPersistenceAdapter.java
  src/main/java/com/stumeet/server/study/adapter/out/persistance/entity/StudyDomainJpaEntity.java
  src/main/java/com/stumeet/server/study/adapter/out/persistance/entity/StudyJpaEntity.java
  src/main/java/com/stumeet/server/study/adapter/out/persistance/mapper/MeetingRepetitionPersistenceMapper.java
  src/main/java/com/stumeet/server/study/adapter/out/persistance/mapper/StudyPersistenceMapper.java
  src/main/java/com/stumeet/server/study/adapter/out/persistance/mapper/StudyTagPersistenceMapper.java
  src/main/java/com/stumeet/server/study/application/port/in/StudyCreateUseCase.java
  src/main/java/com/stumeet/server/study/application/port/in/StudyDomainCreateUseCase.java
  src/main/java/com/stumeet/server/study/application/port/in/StudyQueryUseCase.java
  src/main/java/com/stumeet/server/study/application/port/in/command/StudyCreateCommand.java
  src/main/java/com/stumeet/server/study/application/port/in/mapper/StudyDomainUseCaseMapper.java
  src/main/java/com/stumeet/server/study/application/port/in/mapper/StudyFieldUseCaseMapper.java
  src/main/java/com/stumeet/server/study/application/port/in/mapper/StudyTagsUseCaseMapper.java
  src/main/java/com/stumeet/server/study/application/port/in/mapper/StudyUseCaseMapper.java
  src/main/java/com/stumeet/server/study/application/port/in/response/StudyDetailResponse.java
  src/main/java/com/stumeet/server/study/application/port/out/StudyCommandPort.java
  src/main/java/com/stumeet/server/study/application/port/out/StudyDomainCommandPort.java
  src/main/java/com/stumeet/server/study/application/port/out/StudyFieldQueryPort.java
  src/main/java/com/stumeet/server/study/application/port/out/StudyTagCommandPort.java
  src/main/java/com/stumeet/server/study/application/service/StudyCreateService.java
  src/main/java/com/stumeet/server/study/application/service/StudyDomainCreateService.java
  src/main/java/com/stumeet/server/study/application/service/StudyQueryService.java
  src/main/java/com/stumeet/server/study/application/service/StudyValidationService.java
  src/main/java/com/stumeet/server/study/domain/RepetitionType.java
  src/main/java/com/stumeet/server/study/domain/Study.java
  src/main/java/com/stumeet/server/study/domain/StudyDomain.java
  src/main/java/com/stumeet/server/study/domain/StudyHeadCount.java
  src/main/java/com/stumeet/server/study/domain/StudyMeetingSchedule.java
  src/main/java/com/stumeet/server/study/domain/StudyPeriod.java
  src/main/java/com/stumeet/server/study/domain/exception/InvalidRepetitionDatesException.java
  src/main/java/com/stumeet/server/study/domain/exception/StudyFieldNotExistsException.java
  src/main/java/com/stumeet/server/study/domain/exception/StudyNotExistsException.java
  src/main/resources/db/migration/V1.4__add_study_table.sql
  src/test/java/com/stumeet/server/stub/RepetitionStub.java
  src/test/java/com/stumeet/server/stub/StudyStub.java
  src/test/java/com/stumeet/server/study/adapter/in/web/StudyCreateApiTest.java
  src/test/java/com/stumeet/server/study/adapter/in/web/StudyQueryApiTest.java
  src/test/java/com/stumeet/server/study/domain/RepetitionTest.java
Labels: D-0

#112 ✅ [STMT-146] File 관련 test case 작성
  src/test/java/com/stumeet/server/common/util/FileUtilTest.java
  src/test/java/com/stumeet/server/common/util/FileValidatorTest.java
  src/test/java/com/stumeet/server/file/application/service/FileUploadServiceTest.java
  src/test/java/com/stumeet/server/stub/MockMultipartFileStub.java
Labels: D-0

#113 🗃️ [STMT-6] 고정 data insert를 위한 data.sql 도입
  src/main/resources/application-local.yml
  src/main/resources/application-prod.yml
  src/main/resources/data.sql
  src/main/resources/db/migration/V1.1__modify_member_level.sql
  src/main/resources/db/migration/V1.2__modify_column_rank_to_tier.sql
  src/main/resources/db/migration/V1.3__create_study_table.sql
  src/main/resources/db/migration/V1.4__create_study_member_table.sql
  src/main/resources/db/migration/V1.5__insert_study_field_data.sql
  src/main/resources/db/migration/V1.6__insert_study_dummy_data.sql
  src/test/resources/db/setup.sql
  src/test/resources/db/teardown.sql
Labels: D-1

#114 ✨ [STMT-171] 스터디 가입 API 구현
  src/docs/asciidoc/index.adoc
  src/main/java/com/stumeet/server/common/response/ErrorCode.java
  src/main/java/com/stumeet/server/common/response/SuccessCode.java
  src/main/java/com/stumeet/server/studymember/adapter/in/web/StudyMemberJoinApi.java
  src/main/java/com/stumeet/server/studymember/adapter/in/web/mapper/StudyMemberJoinWebAdapterMapper.java
  src/main/java/com/stumeet/server/studymember/adapter/out/persistence/StudyMemberPersistenceAdapter.java
  src/main/java/com/stumeet/server/studymember/application/port/in/StudyMemberValidationUseCase.java
  src/main/java/com/stumeet/server/studymember/application/port/out/StudyMemberValidationPort.java
  src/main/java/com/stumeet/server/studymember/application/service/StudyMemberJoinService.java
  src/main/java/com/stumeet/server/studymember/application/service/StudyMemberValidationService.java
  src/main/java/com/stumeet/server/studymember/domain/exception/AlreadyStudyJoinMemberException.java
  src/main/java/com/stumeet/server/studymember/domain/exception/NotStudyAdminException.java
  src/main/java/com/stumeet/server/studymember/domain/exception/StudyMemberNotJoinedException.java
  src/test/java/com/stumeet/server/stub/StudyMemberStub.java
  src/test/java/com/stumeet/server/studymember/adapter/in/web/StudyMemberJoinApiTest.java
  src/test/java/com/stumeet/server/studymember/application/service/StudyMemberJoinServiceTest.java
  src/test/resources/db/setup.sql
Labels: D-3

#115 ♻️ [STMT-200] 도메인 study 스키마 리팩토링
  src/main/java/com/stumeet/server/study/adapter/in/web/StudyQueryApi.java
  src/main/java/com/stumeet/server/study/adapter/in/web/response/StudyDetailResponse.java
  src/main/java/com/stumeet/server/study/adapter/out/persistance/JpaStudyDomainRepository.java
  src/main/java/com/stumeet/server/study/adapter/out/persistance/JpaStudyFieldRepository.java
  src/main/java/com/stumeet/server/study/adapter/out/persistance/StudyDomainPersistenceAdapter.java
  src/main/java/com/stumeet/server/study/adapter/out/persistance/StudyFieldPersistenceAdapter.java
  src/main/java/com/stumeet/server/study/adapter/out/persistance/StudyTagPersistenceAdapter.java
  src/main/java/com/stumeet/server/study/adapter/out/persistance/entity/StudyDomainJpaEntity.java
  src/main/java/com/stumeet/server/study/adapter/out/persistance/entity/StudyFieldJpaEntity.java
  src/main/java/com/stumeet/server/study/adapter/out/persistance/entity/StudyJpaEntity.java
  src/main/java/com/stumeet/server/study/adapter/out/persistance/entity/StudyTagJpaEntity.java
  src/main/java/com/stumeet/server/study/adapter/out/persistance/mapper/StudyDomainPersistenceMapper.java
  src/main/java/com/stumeet/server/study/adapter/out/persistance/mapper/StudyFieldPersistenceMapper.java
  src/main/java/com/stumeet/server/study/adapter/out/persistance/mapper/StudyPersistenceMapper.java
  src/main/java/com/stumeet/server/study/adapter/out/persistance/mapper/StudyTagPersistenceMapper.java
  src/main/java/com/stumeet/server/study/application/port/in/StudyDomainCreateUseCase.java
  src/main/java/com/stumeet/server/study/application/port/in/StudyQueryUseCase.java
  src/main/java/com/stumeet/server/study/application/port/in/command/StudyCreateCommand.java
  src/main/java/com/stumeet/server/study/application/port/in/mapper/StudyDomainUseCaseMapper.java
  src/main/java/com/stumeet/server/study/application/port/in/mapper/StudyFieldUseCaseMapper.java
  src/main/java/com/stumeet/server/study/application/port/in/mapper/StudyMeetingScheduleUseCaseMapper.java
  src/main/java/com/stumeet/server/study/application/port/in/mapper/StudyPeriodUseCaseMapper.java
  src/main/java/com/stumeet/server/study/application/port/in/mapper/StudyTagsUseCaseMapper.java
  src/main/java/com/stumeet/server/study/application/port/in/mapper/StudyUseCaseMapper.java
  src/main/java/com/stumeet/server/study/application/port/out/StudyDomainCommandPort.java
  src/main/java/com/stumeet/server/study/application/port/out/StudyFieldQueryPort.java
  src/main/java/com/stumeet/server/study/application/port/out/StudyTagCommandPort.java
  src/main/java/com/stumeet/server/study/application/service/StudyCreateService.java
  src/main/java/com/stumeet/server/study/application/service/StudyDomainCreateService.java
  src/main/java/com/stumeet/server/study/application/service/StudyQueryService.java
  src/main/java/com/stumeet/server/study/domain/Study.java
  src/main/java/com/stumeet/server/study/domain/StudyDomain.java
  src/main/java/com/stumeet/server/study/domain/StudyField.java
  src/main/java/com/stumeet/server/study/domain/StudyHeadCount.java
  src/main/java/com/stumeet/server/study/domain/StudyTag.java
  src/main/java/com/stumeet/server/study/domain/exception/StudyFieldNotExistsException.java
  src/main/resources/data.sql
  src/main/resources/db/migration/V1.3__create_study_table.sql
  src/test/java/com/stumeet/server/stub/StudyStub.java
  src/test/java/com/stumeet/server/study/adapter/in/web/StudyCreateApiTest.java
  src/test/resources/db/setup.sql
  src/test/resources/db/teardown.sql
Labels: D-2

#117 ✨ [STMT-254] 활동 도메인 정의
  src/main/java/com/stumeet/server/activity/adapter/out/mapper/ActivityStatusConverter.java
  src/main/java/com/stumeet/server/activity/adapter/out/model/ActivityImageJpaEntity.java
  src/main/java/com/stumeet/server/activity/adapter/out/model/ActivityJpaEntity.java
  src/main/java/com/stumeet/server/activity/adapter/out/model/ActivityLinkedStudyJpaEntity.java
  src/main/java/com/stumeet/server/activity/adapter/out/model/ActivityMemberJpaEntity.java
  src/main/java/com/stumeet/server/activity/adapter/out/model/ActivityParticipantJpaEntity.java
  src/main/java/com/stumeet/server/activity/domain/exception/NotExistsActivityStatusException.java
  src/main/java/com/stumeet/server/activity/domain/model/Activity.java
  src/main/java/com/stumeet/server/activity/domain/model/ActivityCategory.java
  src/main/java/com/stumeet/server/activity/domain/model/ActivityImage.java
  src/main/java/com/stumeet/server/activity/domain/model/ActivityLinkedStudy.java
  src/main/java/com/stumeet/server/activity/domain/model/ActivityMember.java
  src/main/java/com/stumeet/server/activity/domain/model/ActivityParticipant.java
  src/main/java/com/stumeet/server/activity/domain/model/ActivityStatus.java
  src/main/java/com/stumeet/server/activity/domain/model/Assignment.java
  src/main/java/com/stumeet/server/activity/domain/model/AssignmentStatus.java
  src/main/java/com/stumeet/server/activity/domain/model/Default.java
  src/main/java/com/stumeet/server/activity/domain/model/DefaultStatus.java
  src/main/java/com/stumeet/server/activity/domain/model/Meet.java
  src/main/java/com/stumeet/server/activity/domain/model/MeetStatus.java
  src/main/java/com/stumeet/server/common/response/ErrorCode.java
Labels: D-0

#118 ✨ [STMT-168] 스터디 삭제 api 및 s3에 저장된 관련 파일 삭제 기능 구현
  src/main/java/com/stumeet/server/common/exception/handler/GlobalExceptionHandler.java
  src/main/java/com/stumeet/server/common/response/ErrorCode.java
  src/main/java/com/stumeet/server/common/response/SuccessCode.java
  src/main/java/com/stumeet/server/file/adapter/out/S3ImageStorageAdapter.java
  src/main/java/com/stumeet/server/file/application/port/dto/FileUrl.java
  src/main/java/com/stumeet/server/file/application/port/in/FileDeleteUseCase.java
  src/main/java/com/stumeet/server/file/application/port/in/FileUploadUseCase.java
  src/main/java/com/stumeet/server/file/application/port/out/FileCommandPort.java
  src/main/java/com/stumeet/server/file/application/port/out/FileUrl.java
  src/main/java/com/stumeet/server/file/application/service/FileDeleteService.java
  src/main/java/com/stumeet/server/file/application/service/FileUploadService.java
  src/main/java/com/stumeet/server/study/adapter/in/web/StudyDeleteApi.java
  src/main/java/com/stumeet/server/study/adapter/out/persistance/JpaStudyTagRepository.java
  src/main/java/com/stumeet/server/study/adapter/out/persistance/StudyPersistenceAdapter.java
  src/main/java/com/stumeet/server/study/adapter/out/persistance/entity/StudyJpaEntity.java
  src/main/java/com/stumeet/server/study/adapter/out/persistance/mapper/StudyTagPersistenceMapper.java
  src/main/java/com/stumeet/server/study/application/port/in/StudyDeleteUseCase.java
  src/main/java/com/stumeet/server/study/application/port/in/StudyImageUpdateUseCase.java
  src/main/java/com/stumeet/server/study/application/port/out/StudyCommandPort.java
  src/main/java/com/stumeet/server/study/application/service/StudyCreateService.java
  src/main/java/com/stumeet/server/study/application/service/StudyDeleteService.java
  src/main/java/com/stumeet/server/study/application/service/StudyImageUpdateService.java
  src/main/java/com/stumeet/server/study/application/service/StudyUpdateService.java
  src/main/java/com/stumeet/server/study/domain/Study.java
  src/main/java/com/stumeet/server/studymember/adapter/out/persistence/JpaStudyMemberRepository.java
  src/main/java/com/stumeet/server/studymember/adapter/out/persistence/StudyMemberLeavePersistenceAdapter.java
  src/main/java/com/stumeet/server/studymember/application/port/out/StudyMemberLeavePort.java
  src/main/resources/application-local.yml
  src/main/resources/application-prod.yml
  src/test/java/com/stumeet/server/stub/FileStub.java
  src/test/java/com/stumeet/server/stub/MemberStub.java
  src/test/java/com/stumeet/server/stub/StudyMemberStub.java
  src/test/java/com/stumeet/server/study/adapter/in/web/StudyDeleteApiTest.java
  src/test/java/com/stumeet/server/study/adapter/in/web/StudyUpdateApiTest.java
  src/test/java/com/stumeet/server/studymember/adapter/in/web/StudyMemberJoinApiTest.java
  src/test/java/com/stumeet/server/studymember/adapter/out/persistence/JpaStudyMemberRepositoryCustomImplTest.java
  src/test/resources/db/setup.sql
Labels: D-0

#119 ✨ [STMT-254] 활동 도메인과 영속 객체간 매핑 로직 작성
  src/main/java/com/stumeet/server/activity/adapter/out/mapper/ActivityImagePersistenceMapper.java
  src/main/java/com/stumeet/server/activity/adapter/out/mapper/ActivityParticipantPersistenceMapper.java
  src/main/java/com/stumeet/server/activity/adapter/out/mapper/ActivityPersistenceMapper.java
  src/main/java/com/stumeet/server/activity/adapter/out/model/ActivityImageJpaEntity.java
  src/main/java/com/stumeet/server/activity/adapter/out/model/ActivityJpaEntity.java
  src/main/java/com/stumeet/server/activity/adapter/out/model/ActivityParticipantJpaEntity.java
  src/main/java/com/stumeet/server/activity/application/port/in/command/ActivityConstructCommand.java
  src/main/java/com/stumeet/server/activity/domain/model/Activity.java
  src/main/java/com/stumeet/server/activity/domain/model/ActivityCategory.java
  src/main/java/com/stumeet/server/activity/domain/model/ActivityImage.java
  src/main/java/com/stumeet/server/activity/domain/model/ActivityLinkedStudy.java
  src/main/java/com/stumeet/server/activity/domain/model/ActivityMember.java
  src/main/java/com/stumeet/server/activity/domain/model/ActivityParticipant.java
  src/main/java/com/stumeet/server/activity/domain/model/Assignment.java
  src/main/java/com/stumeet/server/activity/domain/model/Default.java
  src/main/java/com/stumeet/server/activity/domain/model/Meet.java
  src/main/resources/db/migration/V1.5__create_activity_table.sql
Labels: D-0
