Repository Stumeet/STUMEET-SERVER, pull requests merged in 2024-02, with the labels that each got.

#7 [STMT-6] :hammer: D-n rule D-day 자동 감소를 위한 스크립트 추가
  .github/workflows/dnrule.yml
Labels: D-5

#4 [STMT-6] :building_construction: 헥사고날 아키텍처 패키지 구조 예시 작성
  src/main/java/com/stumeet/server/account/adapter/in/web/AccountController.java
  src/main/java/com/stumeet/server/account/adapter/out/persistence/AccountJpaEntity.java
  src/main/java/com/stumeet/server/account/adapter/out/persistence/AccountMapper.java
  src/main/java/com/stumeet/server/account/adapter/out/persistence/AccountPersistenceAdapter.java
  src/main/java/com/stumeet/server/account/adapter/out/persistence/JpaAccountRepository.java
  src/main/java/com/stumeet/server/account/application/port/in/AccountUseCase.java
  src/main/java/com/stumeet/server/account/application/port/in/SignupCommand.java
  src/main/java/com/stumeet/server/account/application/port/out/AccountPort.java
  src/main/java/com/stumeet/server/account/application/service/AccountService.java
  src/main/java/com/stumeet/server/account/domain/Account.java
  src/main/java/com/stumeet/server/common/annotation/PersistenceAdapter.java
  src/main/java/com/stumeet/server/common/annotation/UseCase.java
  src/main/java/com/stumeet/server/common/annotation/WebAdapter.java
Labels: D-5

#8 [STMT-6] :hammer: D-n rule D-day 자동 감소를 위한 스크립트 추가 (#7)
  .github/workflows/dnrule.yml
  src/main/java/com/stumeet/server/account/adapter/in/web/AccountController.java
  src/main/java/com/stumeet/server/account/adapter/out/persistence/AccountJpaEntity.java
  src/main/java/com/stumeet/server/account/adapter/out/persistence/AccountMapper.java
  src/main/java/com/stumeet/server/account/adapter/out/persistence/AccountPersistenceAdapter.java
  src/main/java/com/stumeet/server/account/adapter/out/persistence/JpaAccountRepository.java
  src/main/java/com/stumeet/server/account/application/port/in/AccountUseCase.java
  src/main/java/com/stumeet/server/account/application/port/in/SignupCommand.java
  src/main/java/com/stumeet/server/account/application/port/out/AccountPort.java
  src/main/java/com/stumeet/server/account/application/service/AccountService.java
  src/main/java/com/stumeet/server/account/domain/Account.java
  src/main/java/com/stumeet/server/common/annotation/PersistenceAdapter.java
  src/main/java/com/stumeet/server/common/annotation/UseCase.java
  src/main/java/com/stumeet/server/common/annotation/WebAdapter.java
Labels: D-5

#13 [STMT-6] 👷 CI/CD를 위한 github-actions 추가
  .github/workflows/github-actions.yml
  build.gradle
Labels: D-0

#14 [STMT-151] ✨ JWT 생성 및 검증 객체 구현
  build.gradle
  src/main/java/com/stumeet/server/common/token/JwtTokenProvider.java
  src/main/resources/application.properties
  src/main/resources/application.yml
Labels: D-2

#16 [STMT-151] ✨ OAuth2 로그인/회원가입 기능 구현
  src/main/java/com/stumeet/server/ServerApplication.java
  src/main/java/com/stumeet/server/common/auth/config/AuthConfig.java
  src/main/java/com/stumeet/server/common/auth/config/SecurityConfig.java
  src/main/java/com/stumeet/server/common/auth/filter/JwtAuthenticationFilter.java
  src/main/java/com/stumeet/server/common/auth/filter/OAuthAuthenticationFilter.java
  src/main/java/com/stumeet/server/common/auth/handler/ForbiddenAccessHandler.java
  src/main/java/com/stumeet/server/common/auth/handler/InvalidAuthenticationFailureHandler.java
  src/main/java/com/stumeet/server/common/auth/handler/OAuthAuthenticationSuccessHandler.java
  src/main/java/com/stumeet/server/common/auth/handler/UnauthorizedAccessEntryPoint.java
  src/main/java/com/stumeet/server/common/auth/model/AuthenticationHeader.java
  src/main/java/com/stumeet/server/common/auth/model/LoginMember.java
  src/main/java/com/stumeet/server/common/auth/model/OAuthLoginResponse.java
  src/main/java/com/stumeet/server/common/auth/service/JwtAuthenticationService.java
  src/main/java/com/stumeet/server/common/auth/service/OAuthAuthenticationProvider.java
  src/main/java/com/stumeet/server/common/auth/token/StumeetAuthenticationToken.java
  src/main/java/com/stumeet/server/common/client/oauth/OAuthClient.java
  src/main/java/com/stumeet/server/common/client/oauth/kakao/KakaoOAuthClient.java
  src/main/java/com/stumeet/server/common/client/oauth/kakao/KakaoOAuthFeignClient.java
  src/main/java/com/stumeet/server/common/client/oauth/kakao/model/KakaoUserProfileResponse.java
  src/main/java/com/stumeet/server/common/client/oauth/model/OAuthUserProfileResponse.java
  src/main/java/com/stumeet/server/common/config/QuerydslConfig.java
  src/main/java/com/stumeet/server/common/model/ApiResponse.java
  src/main/java/com/stumeet/server/common/token/JwtTokenProvider.java
  src/main/java/com/stumeet/server/member/adapter/in/web/MemberSignupApi.java
  src/main/java/com/stumeet/server/member/adapter/out/persistence/JpaMemberRepository.java
  src/main/java/com/stumeet/server/member/adapter/out/persistence/JpaMemberRepositoryCustom.java
  src/main/java/com/stumeet/server/member/adapter/out/persistence/JpaMemberRepositoryCustomImpl.java
  src/main/java/com/stumeet/server/member/adapter/out/persistence/JpaOAuthLoginRepository.java
  src/main/java/com/stumeet/server/member/adapter/out/persistence/MemberPersistenceAdapter.java
  src/main/java/com/stumeet/server/member/adapter/out/persistence/MemberPersistenceMapper.java
  src/main/java/com/stumeet/server/member/adapter/out/persistence/OAuthLoginPersistenceAdapter.java
  src/main/java/com/stumeet/server/member/adapter/out/persistence/OAuthLoginPersistenceMapper.java
  src/main/java/com/stumeet/server/member/application/port/in/MemberOAuthUseCase.java
  src/main/java/com/stumeet/server/member/application/port/in/MemberQueryUseCase.java
  src/main/java/com/stumeet/server/member/application/port/in/MemberSignupCommand.java
  src/main/java/com/stumeet/server/member/application/port/in/MemberSignupUseCase.java
  src/main/java/com/stumeet/server/member/application/port/out/MemberCommandPort.java
  src/main/java/com/stumeet/server/member/application/port/out/MemberOAuthPort.java
  src/main/java/com/stumeet/server/member/application/port/out/MemberQueryPort.java
  src/main/java/com/stumeet/server/member/application/port/out/OAuthLoginCommandPort.java
  src/main/java/com/stumeet/server/member/application/port/out/OAuthLoginQueryPort.java
  src/main/java/com/stumeet/server/member/application/service/MemberOAuthService.java
  src/main/java/com/stumeet/server/member/application/service/MemberQueryService.java
  src/main/java/com/stumeet/server/member/application/service/MemberService.java
  src/main/java/com/stumeet/server/member/application/service/MemberSignupService.java
  src/main/java/com/stumeet/server/member/domain/Member.java
  src/main/java/com/stumeet/server/member/domain/OAuthLogin.java
  src/main/java/com/stumeet/server/member/domain/OAuthProvider.java
  src/main/java/com/stumeet/server/member/domain/UserRole.java
Labels: D-5

#17 [STMT-6] 👷 CI/CD workflow 수정 - 환경변수 설정
  .github/workflows/ci-cd.yml
  .gitignore
Labels: enhancement, D-0

#22 [STMT-6] 🌱 Response 공통 객체, 예외 처리 관련 클래스 구현
  src/main/java/com/stumeet/server/common/exception/error/Error.java
  src/main/java/com/stumeet/server/common/exception/error/ErrorField.java
  src/main/java/com/stumeet/server/common/exception/handler/GlobalExceptionHandler.java
  src/main/java/com/stumeet/server/common/exception/model/BusinessException.java
  src/main/java/com/stumeet/server/common/model/ApiResponse.java
  src/main/java/com/stumeet/server/common/response/ErrorCode.java
  src/main/java/com/stumeet/server/common/response/SuccessCode.java
Labels: D-0

#24 ✨ [STMT-146] 이미지 업로드를 위한 인터페이스 정의
  src/main/java/com/stumeet/server/file/application/port/in/FileUploadUseCase.java
  src/main/java/com/stumeet/server/file/application/port/out/FileCommandPort.java
  src/main/java/com/stumeet/server/file/application/port/out/FileUrl.java
  src/main/java/com/stumeet/server/file/application/service/FileUploadService.java
Labels: D-1

#27 [STMT-146] :sparkles: 애플 로그인 기능 추가
  src/main/java/com/stumeet/server/common/auth/filter/JwtAuthenticationFilter.java
  src/main/java/com/stumeet/server/common/auth/service/OAuthAuthenticationProvider.java
  src/main/java/com/stumeet/server/common/client/oauth/OAuthClient.java
  src/main/java/com/stumeet/server/common/client/oauth/apple/AppleIdTokenProvider.java
  src/main/java/com/stumeet/server/common/client/oauth/apple/AppleOAuthClient.java
  src/main/java/com/stumeet/server/common/client/oauth/apple/AppleOAuthFeignClient.java
  src/main/java/com/stumeet/server/common/client/oauth/apple/model/ApplePublicKeyResponses.java
  src/main/java/com/stumeet/server/common/client/oauth/kakao/KakaoOAuthClient.java
  src/main/java/com/stumeet/server/common/util/JwtUtil.java
Labels: D-0

#30 ✨ [STMT-146] S3를 활용한 사용자 프로필 이미지 업로드 기능 구현 (#29)
  build.gradle
  src/main/java/com/stumeet/server/common/annotation/StorageAdapter.java
  src/main/java/com/stumeet/server/common/config/AwsS3Config.java
  src/main/java/com/stumeet/server/common/response/ErrorCode.java
  src/main/java/com/stumeet/server/common/util/FileUtil.java
  src/main/java/com/stumeet/server/file/adapter/out/S3ImageStorageAdapter.java
  src/main/java/com/stumeet/server/file/application/service/FileUploadService.java
  src/main/resources/application-local.yml
  src/main/resources/application-prod.yml
Labels: D-0
